from admin_handlers import events_handlers
from admin_handlers import new_event_handlers
from admin_handlers import archive_handlers
from admin_handlers import registration_handlers
from admin_handlers import users_handlers
